#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. The paths of all marked
# images--or of the current image, if no image is marked--are passed via stdin,
# one file path per line.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

readonly KEY="$1";
case "$KEY" in
    "C-c")      tr '\n' ' ' | xclip -selection clipboard ;;
    "C-d")      tr '\n' '\0' | xargs -0 trash ;;
    "C-r")      tr '\n' '\0' | xargs -0 rm ;;
    "C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
esac
