#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument, followed by the paths of
# all marked images or the path of the current image, if no image is marked.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

readonly KEY="$1"; shift
readonly TAGFILE="$HOME/.config/sxiv/tags"

tag_add() {
	>>"$TAGFILE"
	tags=$(dmenu <"$TAGFILE" | tr '\n' ',')
	[ -z "$tags" ] && return
	iptckwed -a "$tags" "$@"
	echo -n "$tags" | tr ',' '\n' | sort - "$TAGFILE" | uniq >"$TAGFILE.new"
	mv -f "$TAGFILE"{.new,}
}

tag_del() {
	tags=$(iptckwed -ql "$@" | cut -f 2 | tr ',' '\n' | sort | uniq | dmenu | tr '\n' ',')
	[ -z "$tags" ] && return
	iptckwed -r "$tags" "$@"
}

case "$KEY" in
"C-c")      echo -n "$@" | xclip -selection clipboard ;;
"C-d")      trash "$@" ;;
"C-g")      gimp "$@" & ;;
"C-t")      tag_add "$@" ;;
"M-t")      tag_del "$@" ;;
esac

